export const square = [
  { class: "square01", show: true, item: "🍸" },
  { class: "square02", show: true, item: "🥃" },
  { class: "square03", show: true, item: "🍺" },
  { class: "square04", show: true, item: "⚪" },
  { class: "square05", show: true, item: "⚪" },
  { class: "square06", show: true, item: "⚪" },
  { class: "square07", show: true, item: "⚪" },
  { class: "square08", show: true, item: "⚪" },
  { class: "square09", show: true, item: "⚪" },
  { class: "square10", show: true, item: "⚪" },
  { class: "square11", show: true, item: "⚪" },
  { class: "square12", show: true, item: "⚪" },
  { class: "square13", show: true, item: "⚪" },
  { class: "square14", show: true, item: "⚪" },
  { class: "square15", show: true, item: "⚪" },
  { class: "square16", show: true, item: "⚪" },
  { class: "square17", show: true, item: "⚪" },
  { class: "square18", show: true, item: "⚪" },
  { class: "square19", show: true, item: "⚪" },
  { class: "square20", show: true, item: "⚪" },
  { class: "square21", show: true, item: "⚪" },
  { class: "square22", show: true, item: "⚪" },
  { class: "square23", show: true, item: "⚪" },
  { class: "square24", show: true, item: "⚪" },
  { class: "square25", show: true, item: "⚪" },
];

export const square_ = [
  { class: "square01", show: true, item: "100.000" },
  { class: "square02", show: true, item: "⚪" },
  { class: "square03", show: true, item: "⚪" },
  { class: "square04", show: true, item: "⚪" },
  { class: "square05", show: true, item: "⚪" },
  { class: "square06", show: true, item: "⚪" },
  { class: "square07", show: true, item: "⚪" },
  { class: "square08", show: true, item: "⚪" },
  { class: "square09", show: true, item: "⚪" },
  { class: "square10", show: true, item: "⚪" },
  { class: "square11", show: true, item: "⚪" },
  { class: "square12", show: true, item: "⚪" },
  { class: "square13", show: true, item: "⚪" },
  { class: "square14", show: true, item: "⚪" },
  { class: "square15", show: true, item: "⚪" },
  { class: "square16", show: true, item: "⚪" },
  { class: "square17", show: true, item: "⚪" },
  { class: "square18", show: true, item: "⚪" },
  { class: "square19", show: true, item: "⚪" },
  { class: "square20", show: true, item: "⚪" },
  { class: "square21", show: true, item: "⚪" },
  { class: "square22", show: true, item: "⚪" },
  { class: "square23", show: true, item: "⚪" },
  { class: "square24", show: true, item: "⚪" },
  { class: "square25", show: true, item: "⚪" },
];
